gText_Birch_Welcome::
	.string "¡Hola!\p"
	.string "$"

gText_Birch_Pokemon::
	.string "Welcome to POKéMON EMERALD ROGUE!\p"
	.string "$"

gText_Birch_MainSpeech::
	.string "En este juego, cada vez que te\n"
	.string "embarques en una aventura…\p"
	.string "¡el mundo y los Pokémon que\n"
	.string "encuentres serán diferentes!\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Ahora…\n"
	.string "Háblame un poco de ti.$"

gText_Birch_BoyOrGirl::
	.string "Elige un avatar$"

gText_Birch_AvatarStyle0::
	.string "Elige una apariencia$"

gText_Birch_AvatarStyle1::
	.string "Elige un estilo de ropa$"

gText_Birch_WhatsYourName::
	.string "Bueno, ¿cómo te llamas?$"

gText_Birch_HappyWithAvatar::
	.string "¿Este es tu avatar?\n"
	.string "(Puedes cambiarlo más adelante)$"

gText_Birch_SoItsPlayer::
	.string "Así que te llamas {PLAYER}{KUN}, ¿no?$"

gText_Birch_YourePlayer::
	.string "¡Ah, muy bien!\p"
	.string "¡{PLAYER}{KUN}!$"

gText_Birch_AreYouReady::
	.string "¡Te espero en mi laboratorio!\p"
	.string "Ven a buscarme cuando llegues.\p"
	.string "$"
