Text_PictureBookShelf:
	.string "Hay una colección de libros\n"
	.string "ilustrados de Pokémon.$"

Text_BookShelf:
	.string "Está llena de libros de todo tipo.$"

Text_PokemonCenterBookShelf:
	.string "¡Revistas Pokémon!\n"
	.string "Amigo Pokémon…\p"
	.string "Guía Pokémon…\n"
	.string "Pokémon adorables…$"

Text_Vase:
	.string "Parece un jarrón caro…\n"
	.string "Echas un vistazo dentro…\p"
	.string "Pero está vacío.$"

Text_EmptyTrashCan:
	.string "Está vacía.$"

Text_ShopShelf:
	.string "Las estanterías rebosan de todo\n"
	.string "tipo de artículos Pokémon.$"

Text_Blueprint:
	.string "¿Es algún tipo de plano?\n"
	.string "¡Es demasiado complicado!$"
