gText_ObtainedTheItem::
	.string "¡Has obtenido {STR_VAR_2}!$"

gText_TheBagIsFull::
	.string "The BAG is full…$"

gText_PutItemInPocket::
	.string "{PLAYER} guardó {STR_VAR_2}\n"
	.string "en el bolsillo {STR_VAR_3}.$"

gText_PlayerFoundOneItem::
	.string "¡{PLAYER} encontró {STR_VAR_2}!$"

gText_TooBadBagIsFull::
	.string "¡Qué pena!\n"
	.string "La Mochila está llena…$"

gText_PlayerPutItemInBag::
	.string "{PLAYER} guardó {STR_VAR_2}\n"
	.string "en la Mochila.$"

gText_ObtainedTheDecor::
	.string "¡Has obtenido {STR_VAR_2}!$"

gText_NoRoomLeftForAnother::
	.string "Too bad! There's no room left for\n"
	.string "another {STR_VAR_2}…$"

gText_TheDecorWasTransferredToThePC::
	.string "{STR_VAR_2} se envió\n"
	.string "al PC.$"
