gText_PkmnTransferredSomeonesPC::
	.string "{STR_VAR_2} se envió\n"
	.string "al PC de alguien.\p"
	.string "Se ha guardado en la\n"
	.string "Caja “{STR_VAR_1}”.$"

gText_PkmnTransferredLanettesPC::
	.string "{STR_VAR_2} se envió\n"
	.string "al PC de Aria.\p"
	.string "Se ha guardado en la\n"
	.string "Caja “{STR_VAR_1}”.$"

gText_PkmnTransferredSomeonesPCBoxFull::
	.string "La Caja “{STR_VAR_3}” del\n"
	.string "PC de alguien estaba llena.\p"
	.string "{STR_VAR_2} se envió a la\n"
	.string "Caja “{STR_VAR_1}”.$"

gText_PkmnTransferredLanettesPCBoxFull::
	.string "La Caja “{STR_VAR_3}” del\n"
	.string "PC de Aria estaba llena.\p"
	.string "{STR_VAR_2} se envió a la\n"
	.string "Caja “{STR_VAR_1}”.$"

gText_NoMoreRoomForPokemon::
	.string "There's no more room for POKéMON!\p"
	.string "The POKéMON BOXES are full and\n"
	.string "can't accept any more!$"

gText_NicknameThisPokemon::
	.string "Do you want to give a nickname to\n"
	.string "this {STR_VAR_1}?$"
