gText_WouldYouLikeToRestYourPkmn::
	.string "Hola, te damos la bienvenida\n"
	.string "al Centro Pokémon.\p"
	.string "Aquí curamos a los Pokémon\n"
	.string "cansados.\p"
	.string "¿Quieres que descansen\n"
	.string "tus Pokémon?$"

gText_IllTakeYourPkmn::
	.string "Muy bien, necesito tus Pokémon\n"
	.string "unos segundos.$"

gText_RestoredPkmnToFullHealth::
	.string "Gracias por esperar.\p"
	.string "Tus Pokémon ya están\n"
	.string "completamente recuperados.$"

gText_WeHopeToSeeYouAgain::
	.string "¡Esperamos volver a verte!$"

gText_WelcomeCutShort::
	.string "Hola, te damos la bienvenida\n"
	.string "al Centro Pokémon.\p"
	.string "Aquí curamos a los Pokémon\n"
	.string "cansados.\p"
	.string "¿Quieres…$"

gText_NoticesGoldCard::
	.string "E-esa ficha…\n"
	.string "¿Será… la FICHA DORADA?\p"
	.string "¡Qué dorado tan brillante!\n"
	.string "¡Las cuatro estrellas relucen!\p"
	.string "He visto a varios Entrenadores con\n"
	.string "la FICHA PLATEADA, pero, {PLAYER},\l"
	.string "eres {MASC}el primer Entrenador{FEM}la primera Entrenadora{ENDG}\l"
	.string "que veo con la FICHA DORADA.\p"
	.string "Bien, {PLAYER}, permíteme el honor\n"
	.string "de curar a tus Pokémon.$"

gText_YouWantTheUsual::
	.string "¡Qué alegría verte, {PLAYER}!\n"
	.string "Lo de siempre, ¿verdad?$"

gText_IllTakeYourPkmn2::
	.string "Muy bien, necesito tus Pokémon\n"
	.string "unos segundos.$"

gText_ThankYouForWaiting::
	.string "Gracias por esperar.$"

gText_WeHopeToSeeYouAgain2::
	.string "¡Esperamos volver a verte!$"
