	.align 2
gText_ConfirmSave::
	.string "¿Quieres guardar la partida?$"

gText_AlreadySavedFile::
	.string "Ya hay una partida guardada.\n"
	.string "¿Quieres sobrescribirla?$"

gText_SavingDontTurnOff::
	.string "GUARDANDO…\n"
	.string "NO APAGUES LA CONSOLA.$"

gText_PlayerSavedGame::
	.string "{PLAYER} guardó la partida.$"

gText_DifferentSaveFile::
	.string "¡ATENCIÓN!\p"
	.string "Ya hay otra partida guardada.\p"
	.string "Si guardas ahora, perderás toda\n"
	.string "la aventura de la otra partida,\l"
	.string "incluidos objetos y Pokémon.\p"
	.string "¿Seguro que quieres guardar y\n"
	.string "sobrescribir la otra partida?$"

gText_SaveError::
	.string "Error al guardar.\p"
	.string "Cambia la memoria\n"
	.string "de seguridad.$"

gText_SavingDontTurnOffPower::
	.string "GUARDANDO…\n"
	.string "NO APAGUES LA CONSOLA.$"
